SELECT pem.create_alert (
    {{ data.name|qtLiteral(conn,True) }}::text,
    {{ data.template_id }}::integer,
    {{ data.agent_id }}::integer,
    {{ data.server_id }}::integer,
    {{ data.database_name|qtLiteral(conn,True) }}::text,
    {{ data.schema_name|qtLiteral(conn,True) }}::text,
    {{ data.package_name|qtLiteral(conn,True) }}::text,
    {{ data.object_name|qtLiteral(conn,True) }}::text,
    ARRAY{{ data.params|qtLiteral(conn) }}::text[],
    {{ data.operator|qtLiteral(conn,True) }}::text,
    ARRAY{{ data.thresholds|qtLiteral(conn) }}::numeric[],
    {{ data.check_frequency }}::integer,
    {{ data.history_retention }}::integer,
    {{ data.enabled|qtLiteral(conn) }}::boolean,
    {{ data.auto_created|qtLiteral(conn) }}::boolean,
    {{ data.email_group_id if data.email_group_id is not none else 'NULL' }}::integer,
    {{ data.send_email|qtLiteral(conn) }}::boolean,
    {{ data.flapping_detected|qtLiteral(conn) }}::boolean,
    {{ data.last_flapping_detection_processed|qtLiteral(conn, True) }}::timestamptz,
    {{ data.send_trap|qtLiteral(conn) }}::boolean,
    {{ data.snmp_trap_version }}::integer,
    {{ data.low_send_trap|qtLiteral(conn) }}::boolean,
    {{ data.low_email_group_id if data.low_email_group_id is not none else 'NULL' }}::integer,
    {{ data.med_send_trap|qtLiteral(conn) }}::boolean,
    {{ data.med_email_group_id if data.med_email_group_id is not none else 'NULL' }}::integer,
    {{ data.high_send_trap|qtLiteral(conn) }}::boolean,
    {{ data.high_email_group_id if data.high_email_group_id is not none else 'NULL' }}::integer,
    {{ data.execute_script|qtLiteral(conn) }}::boolean,
    {{ data.execute_script_on_clear|qtLiteral(conn) }}::boolean,
    {{ data.execute_script_on_pem_server|qtLiteral(conn) }}::boolean,
    {{ data.script_code|qtLiteral(conn,True) }}::text,
    {{ data.submit_to_nagios|qtLiteral(conn) }}::boolean,
    {{ data.cleared_alert_enable|qtLiteral(conn) }}::boolean
)
